server.port=8082
spring.application.name=medical-staff-service

# --- RabbitMQ ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=piedrazul
spring.rabbitmq.password=piedrazul_pass

# --- Base de datos ---
spring.datasource.url=jdbc:postgresql://localhost:5434/medical_db
spring.datasource.username=medical_user
spring.datasource.password=medical_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# --- Keycloak (Resource Server) ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/piedrazul}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/piedrazul/protocol/openid-connect/certs}

# --- Swagger ---
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# --- Redis ---
spring.data.redis.host=localhost
spring.data.redis.port=6379
