package co.unicauca.piedrazul.presentation.view;

import co.unicauca.piedrazul.domain.services.UserService;
import co.unicauca.piedrazul.domain.entities.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Santiago Solarte
 */
public class RegisterFrame extends javax.swing.JFrame {

    private final UserService userService;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterFrame.class.getName());

    public RegisterFrame(UserService userService) {
        this.userService = userService;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRegistrarCuenta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        txtSegundoNombre = new javax.swing.JTextField();
        txtPrimerApellido = new javax.swing.JTextField();
        txtSegundoApellido = new javax.swing.JTextField();
        txtNomUsuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        txtConfirmarContraseña = new javax.swing.JPasswordField();
        cbxRol = new javax.swing.JComboBox<>();
        cbxTipoDoc = new javax.swing.JComboBox<>();
        txtFechaNac = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblIniciarSesion = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        jLabel18.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnRegistrarCuenta.setBackground(new java.awt.Color(51, 51, 255));
        btnRegistrarCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarCuenta.setText("Crear Cuenta");
        btnRegistrarCuenta.setName("btnRegistrarCuenta"); // NOI18N
        btnRegistrarCuenta.addActionListener(this::btnRegistrarCuentaActionPerformed);

        jLabel3.setText("Primer nombre:");
        jLabel3.setName("lblPrimerNombre"); // NOI18N

        jLabel4.setText("Segundo Nombre:");
        jLabel4.setName("lblSegundoNombre"); // NOI18N

        jLabel5.setText("Primer apellido:");
        jLabel5.setName("lblPrimerApellido"); // NOI18N

        jLabel6.setText("Segundo apellido:");
        jLabel6.setName("lblSegundoApellido"); // NOI18N

        jLabel7.setText("Rol:");
        jLabel7.setName("lblRol"); // NOI18N

        jLabel8.setText("Nombre de usuario:");
        jLabel8.setName("lblNombreUsuarioRegistrar"); // NOI18N

        jLabel9.setText("Contraseña");
        jLabel9.setName("lblContraseñaRegistrar"); // NOI18N

        jLabel10.setText("Confirmar contraseña:");
        jLabel10.setName("lblConfirmarContraseña"); // NOI18N

        txtPrimerNombre.setName("txtPrimerNombre"); // NOI18N

        txtSegundoNombre.setName("txtSegundoNombre"); // NOI18N

        txtPrimerApellido.setName("txtPrimerApellido"); // NOI18N

        txtSegundoApellido.setName("txtSegundoApellido"); // NOI18N

        txtNomUsuario.setName("txtNomUsuario"); // NOI18N

        jLabel11.setText("Fecha de nacimiento:");
        jLabel11.setName("lblFechaNac"); // NOI18N

        jLabel12.setText("Correo:");
        jLabel12.setName("lblCorreoRegistrar"); // NOI18N

        txtCorreo.setName("txtCorreo"); // NOI18N

        jLabel14.setText("Tipo de documento:");
        jLabel14.setName("lblTipoDoc"); // NOI18N

        jLabel15.setText("Número de documento:");
        jLabel15.setName("lblNumDocumento"); // NOI18N

        txtNumDoc.setName("txtNumDoc"); // NOI18N

        txtContraseña.setText("jPasswordField1");
        txtContraseña.setName("txtContraseña"); // NOI18N

        txtConfirmarContraseña.setText("jPasswordField2");
        txtConfirmarContraseña.setName("txtConfirmarContraseña"); // NOI18N

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medico", "Terapista", "Agendador", "Administrador" }));
        cbxRol.setName("cbxRol"); // NOI18N

        cbxTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI", "CE", "PA" }));
        cbxTipoDoc.setName("cbxTipoDoc"); // NOI18N

        txtFechaNac.setText("//");
        txtFechaNac.setName("txtFechaNac"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(txtPrimerNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtPrimerApellido))
                                    .addComponent(txtNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(cbxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNumDoc, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxRol, javax.swing.GroupLayout.Alignment.LEADING, 0, 120, Short.MAX_VALUE)
                                        .addComponent(txtSegundoApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSegundoNombre, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(btnRegistrarCuenta))))
                            .addComponent(jLabel11)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSegundoApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(btnRegistrarCuenta)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel10.getAccessibleContext().setAccessibleDescription("");
        jLabel15.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Crear Cuenta");
        jLabel1.setName("lblTituloCrearCuenta"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Regístrate para agendar tus citas médicas en Piedrazul");
        jLabel2.setName("lblTextoInformativoRegistrarUsuario"); // NOI18N

        jLabel13.setText("jLabel13");
        jLabel13.setName("lbLogoRegistrar"); // NOI18N

        jLabel21.setText("¿Ya tienes cuenta?");
        jLabel21.setName("lblYaTienesCuenta"); // NOI18N

        lblIniciarSesion.setText("Inicia sesión");
        lblIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIniciarSesion.setName("lblIniciarSesion"); // NOI18N
        lblIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel21)
                        .addGap(66, 66, 66)
                        .addComponent(lblIniciarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIniciarSesion)
                    .addComponent(jLabel21))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCuentaActionPerformed

        // 1. Capturamos datos
        String username = txtNomUsuario.getText().trim();
        String firstName = txtPrimerNombre.getText().trim();
        String middleName = txtSegundoNombre.getText().trim();
        String firstSurname = txtPrimerApellido.getText().trim();
        String lastSurname = txtSegundoApellido.getText().trim();
        String userType = cbxTipoDoc.getSelectedItem().toString();
        String userRol = cbxRol.getSelectedItem().toString();
        String birthDate = txtFechaNac.getText().trim();
        String docNumber = txtNumDoc.getText().trim();
        String email = txtCorreo.getText().trim();

        //Guardamos la contraseña
        String password = new String(txtContraseña.getPassword());
        String confirmPassword = new String(txtConfirmarContraseña.getPassword());

        // 2. Validamos campos obligatorios
        if (firstName.isEmpty() || firstSurname.isEmpty() || username.isEmpty()
                || birthDate.equals("//") || docNumber.isEmpty() || email.isEmpty() || password.isEmpty()
                || userRol.isEmpty() || userType.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos obligatorios (*)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Comparar las contraseñas
        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos obligatorios (*)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Crear la instancia de la Entidad User (Capa de Dominio)
        User newUser = new User();

        try {
            newUser.setId(Integer.parseInt(docNumber));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El número de documento debe ser solo números.");
            return;
        }
        newUser.setUsername(username);
        newUser.setFirstName(firstName);
        newUser.setMiddleName(middleName);
        newUser.setFirstSurname(firstSurname);
        newUser.setLastName(lastSurname);
        newUser.setUserTypeId(userType);
        newUser.setEmail(email);
        newUser.setBirthDate(birthDate);
        newUser.setState("ACTIVE");

        //Asignamos el ID al rol escogido
        int roleId = switch (userRol) {
            case "Medico" ->
                1;
            case "Terapista" ->
                2;
            case "Agendador" ->
                3;
            case "Administrador" ->
                4;
            default ->
                2;
        };
        newUser.setRoleId(roleId);

        // 5. Llamar al Servicio (Capa de Negocio)
        // El servicio validará el Regex y hará el BCrypt
        String result = userService.registerUser(newUser, password);

        // Manejar la respuesta
        if (result.equals("SUCCESS")) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario registrado exitosamente!");

            // Limpiar campos o volver al Login
            new LoginFrame(userService).setVisible(true);
            this.dispose();
        } else {
            // Error si ell usuario ya existe
            javax.swing.JOptionPane.showMessageDialog(this, result, "Error de registro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarCuentaActionPerformed

    private void lblIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseClicked
        // 1. Creamos la instancia del LoginFrame
        LoginFrame login = new LoginFrame(this.userService);

        // 2. Centramos la ventana
        login.setLocationRelativeTo(null);

        // 3. La hacemos visible
        login.setVisible(true);

        // 4. Cerramos la ventana actual de Registro para no acumular ventanas abiertas
        this.dispose();    }//GEN-LAST:event_lblIniciarSesionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarCuenta;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JComboBox<String> cbxTipoDoc;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JPasswordField txtConfirmarContraseña;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JFormattedTextField txtFechaNac;
    private javax.swing.JTextField txtNomUsuario;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtSegundoNombre;
    // End of variables declaration//GEN-END:variables
}
